version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes --appendfsync everysec --protected-mode no
    # command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec", "--protected-mode" , "no"]



  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  # realtime-data:
  #   build: ./realtime-data
  #   volumes:
  #     - ./.data:/usr/app/scrapped_data
  #     - ./realtime-data/main.js:/usr/app/main.js
  #   depends_on:
  #     - redis

    
volumes:
  redis-insight:
  redis-data: